apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: u-app
spec:
  # 1 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: u-app
  template:
    metadata:
      labels:
        app: u-app
    spec:
      containers:
      - name: u-app
        # Run this image
        image: akashping/node:02
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MONGO_PORT

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-db-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: u-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
        